changecom(<!--,-->)
include(MYDEFS)dnl
# Information Organization & Access

include(MYSECDATA)
include(CONTACT1)
include(CONTACT2)
include(CONTACT3)
include(CourseDescription.md)
include(OverviewObjectives.md)
include(CourseMaterials.md)
include(INSTRUCTOR1)
include(INSTRUCTOR2)
include(INSTRUCTOR3)
include(HelpfulResources.md)
include(Integrity.md)
include(InclusionAccessibility.md)
include(ASSIGNMENTS)
include(Asgt1.md)
include(MYTOPICS)
